/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with a Google ID token
         * @description Verifies the Google ID token obtained on the device, creates the account on first
         *     sign-in, and returns a new token pair.
         */
        post: operations["signInWithGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a one-time sign-in code by email
         * @description Sends a 6-digit one-time code to the address. Always answers 202 for a well-formed
         *     address, whether or not an account exists, so the endpoint cannot be used to find
         *     accounts. Rate-limited per address and per IP.
         */
        post: operations["startEmailSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange an emailed code for tokens
         * @description Verifies the one-time code, creates the account on first sign-in, and returns a new
         *     token pair. A code is single-use; after 5 wrong attempts it is invalidated and the
         *     user must request a new one.
         */
        post: operations["verifyEmailSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token
         * @description Exchanges a refresh token for a new access token and a new refresh token. The old
         *     refresh token is invalidated; the new one is valid for 90 days from this refresh
         *     (see `TokenPair.refresh_token`). Presenting an already-rotated refresh token is treated
         *     as theft: the whole session (every token descended from the same sign-in) is
         *     revoked and the user must sign in again.
         */
        post: operations["refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push local changes and pull server changes
         * @description One round trip of offline-first sync.
         *
         *     **Push.** `changes` carries every record the device created, edited or deleted since
         *     its last successful sync. Each record carries `version`: the server version the
         *     device last saw for that record (0 for a record the server has never seen). The
         *     server applies a record only when that version matches the stored one, then stores
         *     it as `version + 1`. Every pushed record appears in exactly one of `applied` or
         *     `conflicts` in the response.
         *
         *     **Conflicts.** On a version mismatch the edit with the later `updated_at` wins for
         *     the whole record (ties go to the server). The losing copy is kept in the server's
         *     conflict log. `conflicts[].resolution` says which side won and `server_record` is
         *     the record as now stored; the device replaces its local copy with it.
         *
         *     **Retries are idempotent.** A device that loses the response to a successful sync
         *     re-sends the same records with the same, now stale, `version`. A retry is any
         *     pushed record whose content, apart from `version` and `updated_at`, is identical to
         *     the stored record (`updated_at` is excluded because the server may have clamped it
         *     on the first attempt). The backend resolves each retry as a conflict with
         *     `resolution: server_won`, `client_version` = the version the device sent and a
         *     `server_record` equal to the stored record. Nothing is written and
         *     nothing is lost, so the backend does not add these to the conflict log. The app
         *     must not surface them as real conflicts: when every field of `server_record` except
         *     `version` and `updated_at` equals the copy it pushed, it silently adopts
         *     `server_record.version` and `server_record.updated_at`.
         *     Any other `server_won` or `client_won` result is a real conflict.
         *
         *     **Deletes** are soft: set `deleted_at`. Tombstones travel like any other change so
         *     the delete reaches every device.
         *
         *     **Pull.** `changes` in the response holds records changed on the server since the
         *     request `cursor` (all of the user's records when `cursor` is null; tombstones may be
         *     omitted then). Records the device just pushed are not echoed back; their new
         *     versions are in `applied`. If `has_more` is true, call again with the returned
         *     cursor and no changes until it is false.
         *
         *     **Record ids** are UUIDs made on the device. Records that are unique per natural
         *     key use a deterministic UUIDv5 so two offline devices produce the same id:
         *     UUIDv5 (RFC 9562, formerly RFC 4122: SHA-1, version 5) with namespace = the
         *     user's id (`User.id`, parsed as a UUID) and name = the UTF-8 bytes of
         *     `<table>:<key>` (never case-folded). The resulting id is written in lowercase
         *     canonical form. The key per table:
         *
         *     | Table | Key | Example name |
         *     | --- | --- | --- |
         *     | `profiles` | the literal `me` | `profiles:me` |
         *     | `settings` | the literal `me` | `settings:me` |
         *     | `day_notes`, `workouts`, `weights`, `measurements` | `date` as `YYYY-MM-DD` | `day_notes:2026-10-08` |
         *     | `lift_stats` | the record's `exercise` field, as sent | `lift_stats:Barbell Bench Press` |
         *     | `swaps` | the record's `from` field (the source exercise), as sent | `swaps:Barbell Bench Press` |
         *
         *     Exercise names are used unnormalised: no trimming, case folding or Unicode
         *     normalisation. All other tables use random UUIDv4 ids. Test vectors (user id,
         *     table, key, expected id) are in `packages/api/test-vectors/sync-ids.json`.
         *     Devices send lowercase ids; the server lowercases any id it receives and echoes it
         *     lowercased in `applied` and `conflicts`. The server recomputes the id of every
         *     pushed natural-key record; if one does not match, the whole request fails with 400
         *     `invalid_request` and nothing is applied. The error's `details` entry carries the
         *     record's path in `field` (`changes.<table>[<i>].id`) and the issue
         *     `natural_key_id`, never the id value.
         *
         *     **New records.** A record unknown to the server is stored as version 1 and listed
         *     in `applied`, whatever `version` the device sent.
         *
         *     **Derived data is not synced.** Stores the prototype keeps that can be rebuilt from
         *     synced records have no table. The app rebuilds them locally after every pull; see
         *     `Workout` for the prototype's `sessions` store.
         *
         *     Limits: at most 500 records in total per request and per response page.
         *     `updated_at` values more than 5 minutes in the future are clamped to server time.
         */
        post: operations["sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the shared food database
         * @description Matches `q` against food names and aliases (everyday and Hindi names such as
         *     chawal, anda, dahi), case-insensitively. Results are paged with an opaque cursor.
         */
        get: operations["searchFoods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and version */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download everything the server stores about the signed-in user
         * @description Returns, in one JSON document, every record the server holds for the user: the
         *     account (`user`), every row of every synced table (`profiles` and `settings`
         *     included) and the server's conflict log. The response is built when requested,
         *     so it reflects the server state at `exported_at`; changes still queued on a device
         *     are not in it until they sync.
         *
         *     **Coverage.** `tables` has one array for every `SyncTable` value, always present
         *     (empty when the user has no rows). Records use exactly the `/sync` record schemas,
         *     with their stored `version`, `updated_at` and `deleted_at`. Soft-deleted records
         *     (tombstones) the server still stores are included with `deleted_at` set, so the
         *     export shows everything stored, not only what the app displays. A sync table added
         *     to the contract later is added to the export in the same contract change.
         *
         *     **Not included**, because they are credentials or operational data rather than the
         *     user's data: access and refresh tokens, emailed one-time codes, rate-limit counters
         *     and server logs (which never hold food, weight, health answers or tokens). Progress
         *     photos and other device-only data never reach the server, so the app exports them
         *     on the device.
         *
         *     **Headers.** `Cache-Control: no-store`. `Content-Disposition` suggests a file name,
         *     `plate-and-bar-export-<YYYY-MM-DD>.json` (UTC date of `exported_at`), for browsers.
         *     The server may compress the body when the request allows it (`Accept-Encoding`).
         *
         *     **Rate limit.** At most 5 exports per user per hour, on top of the per-IP limit
         *     every endpoint has; beyond that, 429 `rate_limited` with `Retry-After`.
         *
         *     **Security.** The user id comes only from the access token; there is no way to ask
         *     for another user's export. The backend logs only that an export happened (user id,
         *     time, size), never its content.
         */
        get: operations["exportMyData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete the signed-in user's account and all server-side data
         * @description Permanently deletes the account and everything the server stores for it. There is
         *     no undo and no grace period. The app asks the user to confirm before calling this.
         *
         *     **What is deleted, and when.** Before the server answers 204, in one transaction:
         *     every row of every synced table (tombstones included), the conflict log, the
         *     per-user sync bookkeeping, the account (`User`), its sign-in identities (Google and
         *     email), every refresh token and session, and, for the account's email address,
         *     any pending one-time codes and the wrong-code records kept for rate limiting
         *     (`email_verify_failures`). When the 204 arrives the data is gone from the live
         *     database. Copies in the encrypted nightly backups are not edited; they disappear
         *     when those backups expire, at most 30 days later (backup retention, #36). Server logs
         *     hold no user data to delete. If anything fails, the transaction rolls back, the
         *     server answers 500 and nothing is deleted; the app retries.
         *
         *     **Tokens.** Every refresh token is revoked, so `/auth/refresh` answers 401
         *     `unauthorized`. Access tokens issued before the deletion stay unexpired for up to
         *     15 minutes but are refused by every endpoint with 401 `unauthorized`, except
         *     this one (see Idempotency). Other signed-in devices therefore get 401 on their
         *     next request and must sign in again; no request made with a pre-deletion token
         *     can write data. The server cannot erase data stored on other devices; the app
         *     deletes the local store on the device that made the request.
         *
         *     **Idempotency.** Deleting an account that is already deleted succeeds: a repeat
         *     call with an access token that is still within its lifetime (valid signature,
         *     not expired) whose user no longer exists answers 204 again. A device that lost
         *     the first response can therefore retry. If the access token has expired by then,
         *     the retry gets 401 `token_expired` and the app refreshes as usual. If the refresh
         *     succeeds, the first call never took effect and the app retries with the new token.
         *     If the refresh fails with 401, that does not prove the deletion: the session may
         *     have ended for another reason (expiry, or refresh-token reuse revoking it). The
         *     app must not tell the user the account is deleted on that alone; it says the
         *     deletion could not be confirmed and asks the user to sign in. If that sign-in
         *     returns `new_user: false`, the account still exists and the app offers deletion
         *     again. If it returns `new_user: true`, the old account is gone (and the new,
         *     empty one is the user's to keep or delete).
         *
         *     **Signing in again** with the same Google account or email address afterwards
         *     creates a new, empty account with a new user id (`new_user: true`). Nothing from
         *     the deleted account comes back.
         *
         *     **Rate limit.** The per-user and per-IP limits every endpoint has apply. A 429
         *     means nothing was deleted.
         *
         *     **Security.** The user id comes only from the access token; a user can delete only
         *     their own account. The backend logs that a deletion happened (user id and time)
         *     and nothing else.
         */
        delete: operations["deleteMyAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The one error shape for every 4xx and 5xx response. */
        Error: {
            /**
             * @description Stable machine-readable code. `token_expired`: refresh the access token and
             *     retry. `unauthorized`: sign in again. `invalid_code`: the emailed code is wrong
             *     or expired. `not_found`: reserved for later milestones; no M0 operation
             *     returns it.
             * @enum {string}
             */
            code: "invalid_request" | "unauthorized" | "token_expired" | "invalid_code" | "not_found" | "rate_limited" | "internal" | "unavailable";
            /** @description Plain-language message safe to show the user. Never contains health data. */
            message: string;
            /** @description Per-field problems, for `invalid_request`. */
            details?: {
                /** @description JSON path of the offending field. */
                field: string;
                issue: string;
            }[];
        };
        /**
         * Format: date
         * @description Calendar day in the user's local time, `YYYY-MM-DD`.
         * @example 2026-10-08
         */
        LocalDate: string;
        /**
         * Format: date-time
         * @description ISO 8601 date-time in UTC with a `Z` suffix.
         * @example 2026-10-08T06:30:00Z
         */
        Timestamp: string;
        GoogleSignInRequest: {
            /** @description Google ID token from Google Sign-In on the device. */
            id_token: string;
        };
        EmailStartRequest: {
            /** Format: email */
            email: string;
        };
        EmailStartResponse: {
            code_expires_at: components["schemas"]["Timestamp"];
            /** @description Seconds before another code can be requested for this address. */
            resend_after_seconds: number;
        };
        EmailVerifyRequest: {
            /** Format: email */
            email: string;
            code: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        TokenPair: {
            /** @constant */
            token_type: "Bearer";
            /** @description JWT, short-lived (target 15 minutes). Send as `Authorization: Bearer <token>`. */
            access_token: string;
            access_token_expires_at: components["schemas"]["Timestamp"];
            /**
             * @description Opaque, single-use. Store in secure storage; replace on every refresh.
             *     Lifetime 90 days, extended on rotation: every `/auth/refresh` returns a new
             *     refresh token valid for 90 days from that refresh, so a device that opens the
             *     app at least once every 90 days stays signed in. Presenting an already-rotated
             *     token revokes the whole session.
             */
            refresh_token: string;
            /** @description When `refresh_token` expires, 90 days after it was issued. */
            refresh_token_expires_at: components["schemas"]["Timestamp"];
            user: components["schemas"]["User"];
            /** @description True when this sign-in created the account. */
            new_user: boolean;
        };
        User: {
            /**
             * Format: uuid
             * @description Also the UUIDv5 namespace for deterministic sync record ids.
             */
            id: string;
            /** Format: email */
            email: string | null;
            created_at: components["schemas"]["Timestamp"];
        };
        Health: {
            /** @constant */
            status: "ok";
            /** @description Deployed API build version. */
            version: string;
        };
        FoodPage: {
            items: components["schemas"]["Food"][];
            /** @description Pass as `cursor` for the next page; null on the last page. */
            next_cursor: string | null;
        };
        /** @description A shared food. Values are per serving, as in the prototype; carbs include fibre. */
        Food: {
            /** Format: uuid */
            id: string;
            /**
             * @example Rice
             * @example cooked
             */
            name: string;
            /** @description Everyday Hindi name, when it differs from `name`. */
            name_hi: string | null;
            /** @description Other names matched by search (Hindi, regional and common spellings). */
            aliases: string[];
            serving: components["schemas"]["Serving"];
            per_serving: components["schemas"]["Nutrients"];
            /** @description Fruit and vegetable servings (80 g each) in one serving. */
            fruit_veg_servings: number;
            source: components["schemas"]["FoodSource"];
            updated_at: components["schemas"]["Timestamp"];
        };
        Serving: {
            /**
             * @description Serving as shown to the user. Prototype: `unit`.
             * @example 1 katori (35 g dal)
             * @example 100 g
             * @example 1 glass (250 ml)
             */
            label: string;
            /**
             * @description Grams in the serving label, enabling grams logging (qty = grams / this value).
             *     Null when the label has no gram weight.
             */
            grams: number | null;
        };
        Nutrients: {
            kcal: number;
            protein_g: number;
            /** @description Total carbohydrate including fibre. */
            carbs_g: number;
            /** @description Null when unknown. */
            fibre_g: number | null;
            /** @description Null when unknown. */
            added_sugar_g: number | null;
            fat_g: number;
        };
        /**
         * @description Where a row's values come from. Only the sources listed in ADR 005
         *     (`docs/adr/005-food-data-sources-own-estimates.md`) are allowed.
         */
        FoodSource: {
            /**
             * @description `usda_fdc`: USDA FoodData Central. `fssai`: values derived from FSSAI standards
             *     (paneer, curd, milk). `own_recipe`: calculated from our recipes. `kitchen_test`:
             *     weighed in our kitchen tests. `label_typical`: packaged foods using typical
             *     nutrition-label values across common brands; in the prototype these are whey
             *     protein, Greek yogurt and makhana. `own_estimate`: our own rough estimate, not
             *     weighed or cooked to a recipe (for example restaurant dishes).
             * @enum {string}
             */
            code: "usda_fdc" | "fssai" | "own_recipe" | "kitchen_test" | "label_typical" | "own_estimate";
            /**
             * @example USDA FoodData Central (SR Legacy)
             * @example Typical label values (packaged food)
             */
            name: string;
            /**
             * @example Public domain (CC0 1.0)
             * @example Nutrition facts read from product labels; no label database copied
             */
            licence: string;
            /** Format: uri */
            url: string | null;
            /** @description Identifier in the source, such as a USDA FDC id. */
            reference: string | null;
        };
        SyncRequest: {
            /** @description Opaque cursor from the last successful sync; null on first sync. */
            cursor: string | null;
            changes: components["schemas"]["SyncChanges"];
        };
        SyncResponse: {
            /** @description Opaque; store it and send it with the next sync. */
            cursor: string;
            /** @description True when more server changes are waiting; sync again with `cursor`. */
            has_more: boolean;
            /** @description Pushed records the server stored, with their new versions. */
            applied: components["schemas"]["AppliedRecord"][];
            conflicts: components["schemas"]["SyncConflict"][];
            changes: components["schemas"]["SyncChanges"];
        };
        /** @enum {string} */
        SyncTable: "profiles" | "consents" | "food_logs" | "water_logs" | "day_notes" | "workouts" | "workout_sets" | "lift_stats" | "weights" | "measurements" | "user_foods" | "recipes" | "kitchen_tests" | "exclusions" | "swaps" | "settings";
        AppliedRecord: {
            table: components["schemas"]["SyncTable"];
            /** Format: uuid */
            id: string;
            version: number;
        };
        SyncConflict: {
            table: components["schemas"]["SyncTable"];
            /** Format: uuid */
            id: string;
            /** @description The version the device sent. */
            client_version: number;
            /** @description The version stored on the server after resolution. */
            server_version: number;
            /**
             * @description `client_won`: the device's edit was newer and is now stored. `server_won`: the
             *     server's copy was newer and the device's edit was not applied. Either way the
             *     losing copy is kept in the server's conflict log, except for idempotent retries
             *     (see `POST /sync`), which are not logged.
             * @enum {string}
             */
            resolution: "client_won" | "server_won";
            server_record: components["schemas"]["SyncRecord"];
        };
        /** @description Changed records grouped by table. Omit tables with no changes. */
        SyncChanges: {
            profiles?: components["schemas"]["Profile"][];
            consents?: components["schemas"]["Consent"][];
            food_logs?: components["schemas"]["FoodLog"][];
            water_logs?: components["schemas"]["WaterLog"][];
            day_notes?: components["schemas"]["DayNote"][];
            workouts?: components["schemas"]["Workout"][];
            workout_sets?: components["schemas"]["WorkoutSet"][];
            lift_stats?: components["schemas"]["LiftStat"][];
            weights?: components["schemas"]["Weight"][];
            measurements?: components["schemas"]["Measurement"][];
            user_foods?: components["schemas"]["UserFood"][];
            recipes?: components["schemas"]["Recipe"][];
            kitchen_tests?: components["schemas"]["KitchenTest"][];
            exclusions?: components["schemas"]["Exclusion"][];
            swaps?: components["schemas"]["Swap"][];
            settings?: components["schemas"]["Settings"][];
        };
        /**
         * @description Any synced record. Several record schemas can match the same object, so pick the
         *     schema by the conflict's `table` rather than by validating against each.
         */
        SyncRecord: components["schemas"]["Profile"] | components["schemas"]["Consent"] | components["schemas"]["FoodLog"] | components["schemas"]["WaterLog"] | components["schemas"]["DayNote"] | components["schemas"]["Workout"] | components["schemas"]["WorkoutSet"] | components["schemas"]["LiftStat"] | components["schemas"]["Weight"] | components["schemas"]["Measurement"] | components["schemas"]["UserFood"] | components["schemas"]["Recipe"] | components["schemas"]["KitchenTest"] | components["schemas"]["Exclusion"] | components["schemas"]["Swap"] | components["schemas"]["Settings"];
        /** @description Fields every synced record carries. */
        SyncMeta: {
            /**
             * Format: uuid
             * @description Made on the device. Random UUIDv4, or UUIDv5 for natural-key tables
             *     (encoding under `POST /sync`, Record ids).
             */
            id: string;
            /**
             * @description On push: the server version the device last saw (0 if never synced).
             *     On pull: the stored server version.
             */
            version: number;
            /** @description When the record was last edited on a device. Decides conflicts. */
            updated_at: components["schemas"]["Timestamp"];
            /** @description Set when deleted (tombstone); null otherwise. */
            deleted_at: components["schemas"]["Timestamp"] | null;
        };
        /** @description Everything the server stores for one user (`GET /me/export`). */
        MeExport: {
            /**
             * @description Version of this export layout. Adding a table or a field keeps it at 1; it
             *     changes only if existing content moves or changes meaning.
             * @constant
             */
            format_version: 1;
            /** @description When the server built the export. */
            exported_at: components["schemas"]["Timestamp"];
            user: components["schemas"]["User"];
            tables: components["schemas"]["ExportTables"];
            /**
             * @description Losing copies the server kept when resolving `/sync` conflicts (see
             *     `SyncConflict.resolution`), oldest first. Empty when there were none.
             */
            conflict_log: components["schemas"]["ConflictLogEntry"][];
        };
        /**
         * @description Every synced table (one key per `SyncTable` value) with all of the user's stored
         *     rows, tombstones included. Same record schemas as `SyncChanges`, but every table
         *     is present, as an empty array when the user has no rows.
         */
        ExportTables: {
            profiles: components["schemas"]["Profile"][];
            consents: components["schemas"]["Consent"][];
            food_logs: components["schemas"]["FoodLog"][];
            water_logs: components["schemas"]["WaterLog"][];
            day_notes: components["schemas"]["DayNote"][];
            workouts: components["schemas"]["Workout"][];
            workout_sets: components["schemas"]["WorkoutSet"][];
            lift_stats: components["schemas"]["LiftStat"][];
            weights: components["schemas"]["Weight"][];
            measurements: components["schemas"]["Measurement"][];
            user_foods: components["schemas"]["UserFood"][];
            recipes: components["schemas"]["Recipe"][];
            kitchen_tests: components["schemas"]["KitchenTest"][];
            exclusions: components["schemas"]["Exclusion"][];
            swaps: components["schemas"]["Swap"][];
            settings: components["schemas"]["Settings"][];
        };
        ConflictLogEntry: {
            table: components["schemas"]["SyncTable"];
            /**
             * Format: uuid
             * @description Id of the record the losing copy belongs to.
             */
            id: string;
            /**
             * @description Which side's copy lost: `client` when the conflict resolved `server_won`,
             *     `server` when it resolved `client_won`.
             * @enum {string}
             */
            loser: "client" | "server";
            /** @description The record's version stored after resolution (`SyncConflict.server_version`). */
            winner_version: number;
            /** @description When the server resolved the conflict. */
            logged_at: components["schemas"]["Timestamp"];
            /**
             * @description The losing copy as it was pushed or stored; its `version` is the losing copy's
             *     (for the client, the version it sent). Pick its schema by `table`.
             */
            record: components["schemas"]["SyncRecord"];
        };
        /**
         * @description Setup answers and targets. One per user; id = UUIDv5(`profiles:me`).
         *     Prototype: `settings.profile` plus target fields in `settings`.
         */
        Profile: components["schemas"]["SyncMeta"] & {
            /** @enum {string} */
            sex: "male" | "female";
            age: number;
            /** @description Prototype: `height`. */
            height_cm: number;
            /** @description Weight at setup. Prototype: `weight`. */
            weight_kg: number;
            /** @enum {string} */
            activity: "sitting" | "light" | "feet" | "physical";
            /** @enum {string} */
            where: "gym" | "dumbbells" | "bodyweight";
            /** @description Training days per week; 0 means no plan. */
            days: number;
            /**
             * @description Training experience; null when `days` is 0.
             * @enum {string|null}
             */
            exp: "new" | "some" | "exp" | null;
            /**
             * @description Session length; null when `days` is 0.
             * @enum {integer|null}
             */
            minutes: 30 | 45 | 60 | 75 | 90 | null;
            /** @enum {string} */
            goal: "lose" | "recomp" | "maintain" | "gain";
            /** @enum {string} */
            pace: "gentle" | "moderate";
            /** @enum {string} */
            special: "none" | "pregnant" | "breastfeeding";
            /** @description Answers to the 6 health-check questions, in prototype order. */
            screen: ("yes" | "no")[];
            /** @description Day setup was first completed (drives the beginner ramp). */
            created: components["schemas"]["LocalDate"];
            /** @description Day the user tapped "My doctor has cleared me"; null if not. */
            cleared: components["schemas"]["LocalDate"] | null;
            targets: components["schemas"]["Targets"];
        };
        /** @description Daily targets. Prototype: `settings.kcal`, `.protein`, `.carbs`, `.fat`. */
        Targets: {
            kcal: number;
            protein_g: number;
            carbs_g: number;
            fat_g: number;
        };
        /** @description A dated consent record (DPDP). Prototype: `settings.consent` (a date). */
        Consent: components["schemas"]["SyncMeta"] & {
            /**
             * @description The first-run consent to storing data as described.
             * @enum {string}
             */
            kind: "data_storage";
            given_at: components["schemas"]["Timestamp"];
            /**
             * @description Version of the consent text the user agreed to.
             * @example 2026-10-07
             */
            text_version: string;
        };
        /** @description One logged food in a meal. Prototype: an item in `day.meals`. */
        FoodLog: components["schemas"]["SyncMeta"] & {
            date: components["schemas"]["LocalDate"];
            /** @enum {string} */
            meal: "Breakfast" | "Lunch" | "Snacks" | "Dinner";
            name: string;
            /** @description Number of servings. */
            qty: number;
            /** @description Per serving. */
            kcal: number;
            /** @description Per serving. Prototype: `p`. */
            protein_g: number;
            /** @description Per serving, including fibre. Prototype: `c`. */
            carbs_g: number;
            /** @description Per serving. Prototype: `f`. */
            fat_g: number;
            /**
             * Format: uuid
             * @description Shared food or user food this came from, if any.
             */
            food_id: string | null;
        };
        /** @description One drink of water. Prototype: an entry in `day.water`. */
        WaterLog: components["schemas"]["SyncMeta"] & {
            date: components["schemas"]["LocalDate"];
            ml: number;
        };
        /**
         * @description Per-day flags and counts. One per day; id = UUIDv5(`day_notes:<date>`).
         *     Water lives in `water_logs`.
         */
        DayNote: components["schemas"]["SyncMeta"] & {
            date: components["schemas"]["LocalDate"];
            /** @description "I've logged everything" tick; null when never set. */
            complete: boolean | null;
            steps: number | null;
            /** @description Hours slept. */
            sleep: number | null;
            /** @description Fasting day (switches meal ideas to the fasting pool). */
            fast: boolean;
        };
        /**
         * @description The training session(s) for one day. One per day; id = UUIDv5(`workouts:<date>`).
         *     Sets live in `workout_sets`. Prototype: `day.workout`.
         *
         *     The prototype's `sessions` store (`sessions.entries[date] = { t, n }`, used for
         *     template rotation, the weekly streak and the habits meter) has no table: the app
         *     rebuilds it after every pull from `workouts` and `workout_sets`. For each workout
         *     not deleted, `n` = the number of its sets not deleted with `kind: work` and
         *     `done: true`, and `t` = `base`, else `template`, else "Session"; there is an entry
         *     for the workout's `date` only when `n` > 0.
         */
        Workout: components["schemas"]["SyncMeta"] & {
            date: components["schemas"]["LocalDate"];
            /** @description Display name, e.g. "Upper A (dumbbells only)" or "Push A + Pull A". */
            template: string | null;
            /** @description Plan template the session was built from, e.g. "Upper A". */
            base: string | null;
            /**
             * @description Day override of the profile's `where`; null to use the profile.
             * @enum {string|null}
             */
            where: "gym" | "dumbbells" | "bodyweight" | null;
            /** @description Prototype: `cardio`. */
            cardio_min: number | null;
            /** @description Session modifiers (light, short, deload, re-entry). Shape owned by packages/core; stored as-is. */
            mods: {
                [key: string]: unknown;
            };
            /** @description Exercises in session order. */
            exercises: components["schemas"]["WorkoutExercise"][];
            /**
             * @description How the weekly check-in said to build today's session: `light`, `swap` (next
             *     template) or `orig`; null when no choice was made. Prototype: `ciChoice`.
             * @enum {string|null}
             */
            ci_choice: "light" | "swap" | "orig" | null;
        };
        WorkoutExercise: {
            /** @description Exercise name; unique within a workout. */
            name: string;
            /**
             * @description 2 for exercises added by a second session that day.
             * @enum {integer}
             */
            part: 1 | 2;
            /** @description Ladder bridge exercise (2 lighter sets). */
            bridge: boolean;
            /**
             * @description Did form stay solid on every set.
             * @enum {string|null}
             */
            form: "yes" | "no" | null;
            /** @description Working weight found by the ramp. Prototype: `found`. */
            found_kg: number | null;
            /** @description User skipped the find-your-weight ramp. Prototype: `skipRamp`. */
            skip_ramp: boolean;
        };
        /** @description One working or ramp set within a workout. */
        WorkoutSet: components["schemas"]["SyncMeta"] & {
            /**
             * Format: uuid
             * @description Id of the workout this set belongs to; for natural-key workouts, the UUIDv5 of `workouts:<date>`.
             */
            workout_id: string;
            /** @description Matches a `name` in the workout's `exercises`. */
            exercise: string;
            /**
             * @description `ramp` sets are the find-your-weight ramp. Prototype: `ex.ramp`.
             * @enum {string}
             */
            kind: "work" | "ramp";
            /** @description Position within the exercise's sets of this kind. */
            set_index: number;
            /** @description Load; assistance for assisted exercises; null if blank. Prototype: `w`. */
            weight_kg: number | null;
            /** @description Reps, or seconds for holds; null if blank. Prototype: `r`. */
            reps: number | null;
            done: boolean;
            /** @enum {string|null} */
            rate: "easy" | "right" | "hard" | "fail" | null;
            /** @description When the set was ticked done. */
            t: components["schemas"]["Timestamp"] | null;
        };
        LiftSet: {
            weight_kg: number;
            reps: number;
            /** @enum {string|null} */
            rate: "easy" | "right" | "hard" | "fail" | null;
        };
        /** @description An earlier session in a lift record. Prototype: `L.prev`. */
        LiftSession: {
            date: components["schemas"]["LocalDate"];
            sets: components["schemas"]["LiftSet"][];
            /** @enum {string|null} */
            form: "yes" | "no" | null;
        };
        /**
         * @description Per-exercise history used for weight suggestions and stalls.
         *     One per exercise; id = UUIDv5(`lift_stats:<exercise>`). Prototype: `lifts[name]`.
         */
        LiftStat: components["schemas"]["SyncMeta"] & {
            exercise: string;
            /** @description Day of the latest session. */
            date: components["schemas"]["LocalDate"];
            sets: components["schemas"]["LiftSet"][];
            /** @enum {string|null} */
            form: "yes" | "no" | null;
            /** @description Sessions done on this exercise. Prototype: `n`. */
            sessions: number;
            /** @description Day of the first session. */
            first: components["schemas"]["LocalDate"];
            /** @description The session before the latest. */
            prev: (components["schemas"]["LiftSession"] & {
                /**
                 * @description The session before `prev`; used to evaluate 'below the rep range two
                 *     sessions running' against sessions before today (#101). One level only:
                 *     a nested `prev` that has its own `prev` key (even null) fails validation.
                 *     Older records may omit it.
                 */
                prev?: (components["schemas"]["LiftSession"] & unknown) | null;
            }) | null;
            /** @description Last 8 session scores. Prototype: `hist` with `e`. */
            history: {
                date: components["schemas"]["LocalDate"];
                score: number;
            }[];
            /**
             * @description Day the personal-best toast was last shown for this lift, so it shows at most
             *     once a day; null if never shown. Prototype: `pbToast`.
             */
            pb_toast_date: components["schemas"]["LocalDate"] | null;
        };
        /** @description Body weight on a day. One per day; id = UUIDv5(`weights:<date>`). Prototype: `weights.entries`. */
        Weight: components["schemas"]["SyncMeta"] & {
            date: components["schemas"]["LocalDate"];
            /** @description The prototype accepts a weigh-in only above 20 and below 400 kg. */
            weight_kg: number;
        };
        /**
         * @description Tape measurements on a day, in cm; null when not measured.
         *     One per day; id = UUIDv5(`measurements:<date>`). Prototype: `measures.entries`.
         */
        Measurement: components["schemas"]["SyncMeta"] & {
            date: components["schemas"]["LocalDate"];
            waist_cm: components["schemas"]["TapeCm"];
            neck_cm: components["schemas"]["TapeCm"];
            chest_cm: components["schemas"]["TapeCm"];
            arm_cm: components["schemas"]["TapeCm"];
            thigh_cm: components["schemas"]["TapeCm"];
            hips_cm: components["schemas"]["TapeCm"];
        };
        TapeCm: number | null;
        /** @description A personal food. Prototype: an item in `settings.myFoods`. */
        UserFood: components["schemas"]["SyncMeta"] & {
            name: string;
            /** @description Serving label, e.g. "1 katori". */
            unit: string;
            kcal: number;
            protein_g: number;
            /** @description Including fibre. */
            carbs_g: number;
            fat_g: number;
            /** @description Prototype: `fib`. */
            fibre_g: number | null;
            /** @description Prototype: `sug`. */
            added_sugar_g: number | null;
            /** @description Prototype: `veg`. */
            fruit_veg_servings: number | null;
            /**
             * @description Prototype: flags `recipe` / `kitchen`.
             * @enum {string}
             */
            origin: "custom" | "recipe" | "kitchen_test";
        };
        Ingredient: {
            /**
             * @description Raw ingredient name from the shared raw table. Prototype: `ing`.
             * @example Toor dal (dry)
             */
            ingredient: string;
            /** @description Prototype: `amt`. */
            amount: number;
            /** @enum {string} */
            unit: "g" | "tsp" | "tbsp";
        };
        /** @description A home recipe built from raw ingredients. Prototype: an item in `settings.recipes`. */
        Recipe: components["schemas"]["SyncMeta"] & {
            name: string;
            ingredients: components["schemas"]["Ingredient"][];
            /**
             * @description How the cooked yield is given. Prototype: `ymode`.
             * @enum {string}
             */
            yield_mode: "katori" | "grams";
            /** @description Katoris (150 g each) the recipe made, when `yield_mode` is katori. */
            katoris: number | null;
            /** @description Cooked weight, when `yield_mode` is grams. Prototype: `grams`. */
            cooked_g: number | null;
            /**
             * @description Oil level chosen in the recipe builder.
             * @example normal
             */
            oil: string;
        };
        /**
         * @description A weighed dish. Photos stay on the device; only `has_photo` syncs.
         *     Prototype: an item in `settings.kitchen`.
         */
        KitchenTest: components["schemas"]["SyncMeta"] & {
            name: string;
            date: components["schemas"]["LocalDate"];
            note: string;
            ingredients: components["schemas"]["Ingredient"][];
            /** @description Empty pot weight. Prototype: `pot`. */
            pot_g: number | null;
            /** @description Pot with cooked food. Prototype: `potFull`. */
            pot_full_g: number | null;
            /** @description Cooked weight entered directly. Prototype: `cooked`. */
            cooked_g: number | null;
            /** @description Weight of one serving. Prototype: `serving`. */
            serving_g: number | null;
            /**
             * @description Prototype: `sname`.
             * @enum {string}
             */
            serving_name: "katori" | "plate" | "piece" | "glass" | "bowl";
            /** @description A photo exists on the device. Prototype: `hasPhoto`. */
            has_photo: boolean;
        };
        /** @description A rule leaving an exercise, family, pattern or joint out. Prototype: an item in `settings.excl`. */
        Exclusion: components["schemas"]["SyncMeta"] & {
            /** @description Exercise the user was looking at when making the rule. */
            name: string;
            /** @enum {string} */
            scope: "exercise" | "family" | "pattern" | "joint";
            /** @description Exercise name, family, pattern or joint, per `scope`. */
            key: string;
            /** @enum {string|null} */
            reason: "pain" | "equip" | "dislike" | "form" | null;
            created: components["schemas"]["LocalDate"];
            /** @description Last day of a timed rule; null for permanent. */
            until: components["schemas"]["LocalDate"] | null;
            /** @description Replacement picked per exercise name; null value means skipped. */
            to: {
                [key: string]: string | null;
            };
            /** @description The user brought the exercise back; rule no longer active. */
            done: boolean;
        };
        /**
         * @description A lasting swap of one exercise for another (ladder step or side swap).
         *     One per source exercise; id = UUIDv5(`swaps:<from>`). Prototype: `settings.repl[from]`.
         */
        Swap: components["schemas"]["SyncMeta"] & {
            from: string;
            to: string;
            since: components["schemas"]["LocalDate"];
            /** @description Last day the old exercise is kept as a bridge. Prototype: `bridgeUntil`. */
            bridge_until: components["schemas"]["LocalDate"] | null;
        };
        /** @description Tags for a custom exercise, same meaning as content tags (`p`, `f`, `eq`, `d`, `m`, `s`, `j`). */
        ExerciseTags: {
            pattern: string;
            family: string;
            equipment: string;
            difficulty: number;
            primary: components["schemas"]["Muscle"][];
            secondary: components["schemas"]["Muscle"][];
            joints: string[];
        };
        /** @enum {string} */
        Muscle: "chest" | "front-delt" | "side-delt" | "rear-delt" | "triceps" | "lats" | "upper-back" | "biceps" | "forearms" | "quads" | "hams" | "glutes" | "calves" | "abs" | "lower-back";
        /**
         * @description Training and app preferences. One per user; id = UUIDv5(`settings:me`).
         *     Prototype: the remaining keys of `settings` (profile, targets, consent, myFoods,
         *     recipes, kitchen, excl and repl have their own tables). `labHold` is not synced in
         *     v0: lab reports are a v2 feature and whether the hold flag syncs is decided with them.
         */
        Settings: components["schemas"]["SyncMeta"] & {
            /** @description Focus muscles. */
            focus: components["schemas"]["Muscle"][];
            /** @description Rest timer turned off. Prototype: `restOff`. */
            rest_off: boolean;
            /** @description Tags for custom exercises, keyed by exercise name. Prototype: `customTags`. */
            custom_tags: {
                [key: string]: components["schemas"]["ExerciseTags"];
            };
            /**
             * @description Meal-idea diet filter: everything, eggetarian or vegetarian.
             * @enum {string}
             */
            diet: "any" | "egg" | "veg";
            /** @description Prototype: `water`. */
            water_sizes: {
                glass_ml: number;
                bottle_ml: number;
            };
            /** @description Per-exercise type, step and rep range, keyed by exercise name. Prototype: `ex`. */
            exercise_overrides: {
                [key: string]: {
                    type: string;
                    step_kg: number;
                    rep_low: number;
                    rep_high: number;
                };
            };
            /**
             * @description Calorie moves between days (last 7 days). One "bigger meal" plan adds several
             *     entries: the extra kcal on its day and an equal cut on each of the next days.
             *     All entries of one plan share an `id`, and undo removes every entry with that id.
             */
            flex: {
                /**
                 * Format: uuid
                 * @description Id of the flex plan this entry belongs to: a random UUIDv4 made on the device
                 *     when the plan is made. Every entry of the plan has the same id, so it is not
                 *     unique within `flex`. Undo removes all entries with this id. Prototype: `id`.
                 */
                id: string;
                date: components["schemas"]["LocalDate"];
                /** @description Prototype: `d`. */
                kcal_delta: number;
            }[];
            /** @description Exercises coming back after an exclusion, keyed by name, with the last day of the light period. */
            returning: {
                [key: string]: {
                    until: components["schemas"]["LocalDate"];
                };
            };
            /** @description Ladder "stay" answers, keyed by exercise name, until a day. Prototype: `ladderStay`. */
            ladder_stay: {
                [key: string]: components["schemas"]["LocalDate"];
            };
            /** @description Monday of the last weekly check-in seen. Prototype: `checkinSeen`. */
            checkin_seen: components["schemas"]["LocalDate"] | null;
            /** @description Plan adjustment state (declines, muted, dismissed, deload, reentry). Prototype: `adj`. Shape owned by packages/core. */
            adjustments: {
                [key: string]: unknown;
            };
            /** @description Real-burn estimate state. Shape owned by packages/core. */
            adaptive: {
                [key: string]: unknown;
            };
            /** @description Science-card progress. Shape owned by packages/core. */
            learn: {
                [key: string]: unknown;
            };
            /** @description Saved meal plan. Prototype: `mealPlan`. Shape owned by packages/core. */
            meal_plan: {
                [key: string]: unknown;
            } | null;
            /** @description Meal-prep batches still being eaten. Shape owned by packages/core. */
            prep: {
                [key: string]: unknown;
            }[];
        };
    };
    responses: {
        /** @description Signed in; a new token pair. */
        TokenPair: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["TokenPair"];
            };
        };
        /** @description The request is malformed or fails validation. */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, invalid or expired credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests. Retry after the number of seconds in `Retry-After`. */
        RateLimited: {
            headers: {
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signInWithGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleSignInRequest"];
            };
        };
        responses: {
            200: components["responses"]["TokenPair"];
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    startEmailSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailStartRequest"];
            };
        };
        responses: {
            /** @description Code sent (or silently not sent if the address cannot receive mail). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailStartResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    verifyEmailSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerifyRequest"];
            };
        };
        responses: {
            200: components["responses"]["TokenPair"];
            400: components["responses"]["InvalidRequest"];
            /** @description Code wrong, expired, already used, or attempts exhausted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            200: components["responses"]["TokenPair"];
            400: components["responses"]["InvalidRequest"];
            /** @description Refresh token unknown, expired, revoked or reused. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    sync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Sync round trip completed (individual records may still be in conflict). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    searchFoods: {
        parameters: {
            query: {
                /**
                 * @description Search text, matched against name and aliases.
                 * @example dahi
                 */
                q: string;
                /**
                 * @description Opaque cursor from a previous page's `next_cursor`.
                 * @example f_20
                 */
                cursor?: string;
                /**
                 * @description Page size.
                 * @example 20
                 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of matching foods. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodPage"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            429: components["responses"]["RateLimited"];
            /** @description The API is up but cannot serve requests (for example, the database is unreachable). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    exportMyData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user's data. */
            200: {
                headers: {
                    /** @description `attachment; filename="plate-and-bar-export-<YYYY-MM-DD>.json"` */
                    "Content-Disposition"?: string;
                    /** @description Always `no-store`. */
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeExport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    deleteMyAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account and all its server-side data are deleted (or were already). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
}
