/** Copy for the data screen (#27). No message holds any user data. */
export const DATA_COPY = {
  title: 'Your data',
  intro: 'Download a copy of what the app stores, or delete everything.',
  exportDevice: 'Download my data',
  exportServer: 'Download from my account',
  exportHint: 'The download works without a connection: it is made from what is on this device. Progress photos, cycle and lab data stay on this device.',
  signInToExport: 'Sign in to download from your account',
  exportLinkedHint: 'This device is linked to an account but you are signed out. Sign in to download what the server holds for it.',
  exportServerHint: 'You are signed in, so you can also download what our server holds for your account. That needs a connection.',
  exporting: 'Preparing…',
  exportSaved: (name: string) => `Saved ${name}.`,
  exportShared: 'Your data is ready to save or share.',
  exportNoShare: 'Sharing is not available on this device.',
  exportFailed: 'Could not make the file. Nothing was changed.',
  serverOffline: 'You are offline. The account download needs a connection; the device download still works.',
  serverUnavailable: 'The server could not be reached right now. Try again later.',
  serverSession: 'Your session has ended. Sign in again to download from your account.',
  serverRate: (sec: number) => `You can download from your account up to 5 times an hour. Try again in about ${Math.ceil(sec / 60)} min.`,
  delete: 'Delete everything',
  confirmTitle: 'Delete everything?',
  confirmDevice: 'This permanently deletes everything on this device: your profile and targets, food, water and workout logs, weights, measurements, your own foods and recipes, settings and anything waiting to sync. It cannot be undone.',
  confirmNoAccount: 'This device is not linked to an account, so this deletes the data on this device only.',
  confirmLinkedSignedOut: 'This device is linked to an account, but you are signed out. To delete the account and its data on our server, sign in first. Deleting only this device leaves your account and its server data in place.',
  signInToDelete: 'Sign in to delete your account',
  deleteDeviceOnly: 'Delete only this device',
  confirmDeviceOnly: 'Delete only this device? Your account and its data on our server stay. You can sign in again later to get them back.',
  finishDevice: 'Finish deleting this device',
  confirmAccount: 'Because you are signed in, it also deletes your account and everything stored for it on our server, and signs you out. Server backups are removed within 30 days. Deleting the account needs a connection.',
  confirmDelete: 'Yes, delete everything',
  deleting: 'Deleting…',
  cancel: 'Cancel',
  done: 'Done',
  deletedAll: 'Your account and the data on this device are deleted.',
  deletedLocal: 'The data on this device is deleted.',
  noticeAll: 'Everything deleted. Your account and the data on this device are gone.',
  noticeDevice: 'This device was cleared. Your account still exists.',
  offline: 'You are offline, so nothing was deleted. Your account is stored on our server, so deleting needs a connection. Try again when you are online.',
  unavailable: 'The server could not delete your account right now, so nothing was deleted. Try again later.',
  rate: (sec: number) => `Too many tries, so nothing was deleted. Try again in about ${Math.ceil(sec / 60)} min.`,
  unconfirmed: 'We could not confirm the deletion, and nothing on this device was deleted. Sign in again, then try deleting again.',
  needsSignIn: 'This device is linked to an account. Sign in to delete it, or delete only this device.',
  ownerChanged: 'Another account was signed in on this device meanwhile, so nothing on this device was deleted.',
  ownerChangedAfterDelete: 'Your account was deleted. This device was not cleared, because another account signed in on it meanwhile.',
  localFailed: 'Your account is deleted, but this device could not clear its data. Tap delete again to finish.',
};
