/** Copy for the data screen (#27). No message holds any user data. */
export const DATA_COPY = {
  title: 'Your data',
  intro: 'Download a copy of what the app stores, or delete everything.',
  exportDevice: 'Download my data',
  exportServer: 'Download from my account',
  exportHint: 'The download works without a connection: it is made from what is on this device. Progress photos, cycle and lab data stay on this device.',
  exportServerHint: 'You are signed in, so you can also download what our server holds for your account. That needs a connection.',
  exporting: 'Preparing…',
  exportSaved: (name: string) => `Saved ${name}.`,
  exportShared: 'Your data is ready to save or share.',
  exportNoShare: 'Sharing is not available on this device.',
  exportFailed: 'Could not make the file. Nothing was changed.',
  serverOffline: 'You are offline. The account download needs a connection; the device download still works.',
  serverUnavailable: 'The server could not be reached right now. Try again later.',
  serverSession: 'Your session has ended. Sign in again to download from your account.',
  serverRate: (sec: number) => `You can download from your account up to 5 times an hour. Try again in about ${Math.ceil(sec / 60)} min.`,
  delete: 'Delete everything',
  confirmTitle: 'Delete everything?',
  confirmDevice: 'This permanently deletes everything on this device: your profile and targets, food, water and workout logs, weights, measurements, your own foods and recipes, settings and anything waiting to sync. It cannot be undone.',
  confirmDeviceSignedOut: 'Nothing is stored on a server for you, because you are not signed in.',
  confirmAccount: 'Because you are signed in, it also deletes your account and everything stored for it on our server, and signs you out. Server backups are removed within 30 days. Deleting the account needs a connection.',
  confirmDelete: 'Yes, delete everything',
  deleting: 'Deleting…',
  cancel: 'Cancel',
  done: 'Done',
  deletedAll: 'Your account and the data on this device are deleted.',
  deletedLocal: 'The data on this device is deleted.',
  offline: 'You are offline, so nothing was deleted. Your account is stored on our server, so deleting needs a connection. Try again when you are online.',
  unavailable: 'The server could not delete your account right now, so nothing was deleted. Try again later.',
  rate: (sec: number) => `Too many tries, so nothing was deleted. Try again in about ${Math.ceil(sec / 60)} min.`,
  unconfirmed: 'We could not confirm the deletion, and nothing on this device was deleted. Sign in again, then try deleting again.',
  localFailed: 'Your account is deleted, but this device could not clear its data. Tap delete again to finish.',
};
