-- Identity columns use utf8mb4_bin: ADR 004 allows only trim and lower-case normalisation (done in
-- the application), so the database must not fold case or accents on these keys.
-- Accounts and sessions (ADR 003, ADR 004). Sync tables arrive in a later migration (#28).
-- Timestamps are UTC. Ids are UUIDs generated by the application.

CREATE TABLE users (
    id         CHAR(36)     NOT NULL,
    email      VARCHAR(320) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL COMMENT 'trimmed, lower-cased; NULL if the account has no email',
    created_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_email (email)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- Many identities per user; lookup is by (provider, provider_subject).
-- For email-code sign-in the subject is the normalised email.
CREATE TABLE auth_identities (
    id               CHAR(36)     NOT NULL,
    user_id          CHAR(36)     NOT NULL,
    provider         VARCHAR(16)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'google | email | apple',
    provider_subject VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    created_at       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_auth_identities_subject (provider, provider_subject),
    KEY ix_auth_identities_user (user_id),
    CONSTRAINT fk_auth_identities_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- Opaque single-use refresh tokens, stored as a SHA-256 hex digest only.
-- family_id is shared by every token descended from one sign-in, so reuse of a
-- rotated token can revoke the whole family.
CREATE TABLE refresh_tokens (
    id         CHAR(36)    NOT NULL,
    user_id    CHAR(36)    NOT NULL,
    family_id  CHAR(36)    NOT NULL,
    token_hash CHAR(64)    CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    rotated_at DATETIME(3) NULL COMMENT 'set when exchanged for a new token; presenting it again is reuse',
    revoked_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_refresh_tokens_hash (token_hash),
    KEY ix_refresh_tokens_family (family_id),
    KEY ix_refresh_tokens_user (user_id),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
