#!/usr/bin/env bash
# Patch the Gradle file generated by `expo prebuild` so the release build type
# is signed with the upload keystore when one is supplied through environment
# variables. Without them the file is left untouched and the Expo template
# debug-signs the release build (installable, not uploadable to Play).
#
# Usage: android-signing.sh <path to android/app/build.gradle>
# Env (all four required to sign): ANDROID_KEYSTORE_FILE, ANDROID_KEYSTORE_PASSWORD,
# ANDROID_KEY_ALIAS, ANDROID_KEY_PASSWORD
set -euo pipefail

gradle_file="${1:?usage: android-signing.sh <android/app/build.gradle>}"

if [ -z "${ANDROID_KEYSTORE_FILE:-}" ] || [ -z "${ANDROID_KEYSTORE_PASSWORD:-}" ] \
  || [ -z "${ANDROID_KEY_ALIAS:-}" ] || [ -z "${ANDROID_KEY_PASSWORD:-}" ]; then
  echo "No keystore configured: release build will be debug-signed."
  exit 0
fi

tmp="$(mktemp)"
awk '
  /^    signingConfigs \{/ && !sc {
    print
    print "        release {"
    print "            storeFile file(System.getenv(\"ANDROID_KEYSTORE_FILE\"))"
    print "            storePassword System.getenv(\"ANDROID_KEYSTORE_PASSWORD\")"
    print "            keyAlias System.getenv(\"ANDROID_KEY_ALIAS\")"
    print "            keyPassword System.getenv(\"ANDROID_KEY_PASSWORD\")"
    print "        }"
    sc = 1; next
  }
  /^        release \{/ && sc && !rel { rel = 1 }
  rel && !done && /signingConfig signingConfigs\.debug/ {
    sub(/signingConfigs\.debug/, "signingConfigs.release"); done = 1
  }
  { print }
  END { if (!sc || !done) exit 3 }
' "$gradle_file" > "$tmp" || {
  echo "::error::Could not patch $gradle_file: the Expo template changed. Update infra/scripts/android-signing.sh."
  rm -f "$tmp"; exit 1
}
mv "$tmp" "$gradle_file"
echo "Release build will be signed with the supplied keystore."
