#!/usr/bin/env bash
# Patch the Gradle file generated by `expo prebuild` so the release build type
# is signed with the upload keystore when one is supplied through environment
# variables. Without them the file is left untouched and the Expo template
# debug-signs the release build (installable, not uploadable to Play).
#
# Usage: android-signing.sh <path to android/app/build.gradle>
# Env (all four required to sign; none set means debug-signed; some set is an error): ANDROID_KEYSTORE_FILE, ANDROID_KEYSTORE_PASSWORD,
# ANDROID_KEY_ALIAS, ANDROID_KEY_PASSWORD
set -euo pipefail

gradle_file="${1:?usage: android-signing.sh <android/app/build.gradle>}"

set_count=0
for v in ANDROID_KEYSTORE_FILE ANDROID_KEYSTORE_PASSWORD ANDROID_KEY_ALIAS ANDROID_KEY_PASSWORD; do
  [ -n "${!v:-}" ] && set_count=$((set_count + 1))
done

if [ "$set_count" -eq 0 ]; then
  echo "No keystore configured: release build will be debug-signed."
  exit 0
fi
if [ "$set_count" -ne 4 ]; then
  echo "::error::Only $set_count of 4 signing inputs are set (ANDROID_KEYSTORE_BASE64, ANDROID_KEYSTORE_PASSWORD, ANDROID_KEY_ALIAS, ANDROID_KEY_PASSWORD). Set all four or none."
  exit 1
fi

# Idempotent: already patched
if grep -q 'signingConfigs\.release' "$gradle_file"; then
  echo "Release signing already configured in $gradle_file."
  exit 0
fi

tmp="$(mktemp)"
awk '
  /^    signingConfigs \{/ && !sc {
    print
    print "        release {"
    print "            storeFile file(System.getenv(\"ANDROID_KEYSTORE_FILE\"))"
    print "            storePassword System.getenv(\"ANDROID_KEYSTORE_PASSWORD\")"
    print "            keyAlias System.getenv(\"ANDROID_KEY_ALIAS\")"
    print "            keyPassword System.getenv(\"ANDROID_KEY_PASSWORD\")"
    print "        }"
    sc = 1; next
  }
  /^    buildTypes \{/ { bt = 1 }
  bt && /^        release \{/ { rel = 1 }
  rel && !done && /signingConfig signingConfigs\.debug/ {
    sub(/signingConfigs\.debug/, "signingConfigs.release"); done = 1
  }
  { print }
  END { if (!sc || !done) exit 3 }
' "$gradle_file" > "$tmp" || {
  echo "::error::Could not patch $gradle_file: the Expo template changed. Update infra/scripts/android-signing.sh."
  rm -f "$tmp"; exit 1
}
mv "$tmp" "$gradle_file"
echo "Release build will be signed with the supplied keystore."
