import bundledMeta from './bundled.json';

/** A content bundle as this build holds it: hash of its exact bytes, own schema_version, last-change time (UTC ISO). */
export interface BundleMeta {
  sha256: string;
  schema_version: number;
  updated_at: string;
}

/**
 * Bundled bundles by name (generated by scripts/content-meta.mjs). The keys are the names the app knows; the bundled
 * schema_version is the only one this build supports for that name, since readers import the bundled shape.
 */
export const BUNDLED: Readonly<Record<string, BundleMeta>> = bundledMeta;
